adobe/aepsdk-react-native

README.md

Enable the CircleCI badge

---

README.md
packages/core/README.md
packages/userprofile/README.md

Add the SDK initialization docs to READMEs

---

apps/AEPSampleApp/App.js
apps/AEPSampleApp/extensions/Core.js
apps/AEPSampleApp/ios/Podfile.lock
tests/jest/setup.ts

Update podfile and minor clean up
Update podfile and minor clean up

Update podfile and minor clean up

---

packages/userprofile/README.md
packages/userprofile/package.json

UserProfile (1.0.0-alpha.3) -> main

---

packages/userprofile/README.md
packages/userprofile/package.json

UserProfile (1.0.0-alpha.3) -> staging  (#50)

---

apps/AEPSampleApp/package.json
packages/edge/package.json
packages/messaging/package.json

To fix an npm incompatible issue, we need to update the version range of AEP plugins to only include alpha versions in  `peerDependecies`.

Edge (1.0.0-alpha.2), Messaging (1.0.0-alpha.2) -> staging 

---

apps/AEPSampleApp/extensions/Identity.js

Fix a typo in sample app
Fix a typo in sample app

Fix a typo in sample app

---

packages/edgeidentity/android/src/main/java/com/adobe/marketing/mobile/reactnative/edgeidentity/RCTAEPEdgeIdentityModule.java

Remove the unused import statements

Remove the unused import statements

---

packages/edgeidentity/README.md

fix a typo in readme

---

apps/AEPSampleApp/extensions/Core.js
apps/AEPSampleApp/ios/Podfile.lock
apps/AEPSampleApp/package.json
packages/core/__tests__/AEPCoreTests.ts
packages/core/android/src/main/java/com/adobe/marketing/mobile/reactnative/RCTAEPCoreModule.java
packages/core/ios/src/Core/RCTAEPCore.m
packages/core/js/AEPCore.js
packages/core/js/index.d.ts
packages/core/package.json
tests/jest/setup.ts
yarn.lock

* add a new API in Core -> resetIdentities
* upgrade core package version to 1.0.0-alpha.2

Core (1.0.0-alpha.2) -> staging

---

README.md

add the FAQ section in main README

---

packages/edge/android/src/main/java/com/adobe/marketing/mobile/reactnative/edge/RCTAEPEdgeArrayUtil.java
packages/edge/android/src/main/java/com/adobe/marketing/mobile/reactnative/edge/RCTAEPEdgeDataBridge.java
packages/edge/android/src/main/java/com/adobe/marketing/mobile/reactnative/edge/RCTAEPEdgeMapUtil.java
packages/edge/android/src/main/java/com/adobe/marketing/mobile/reactnative/edge/RCTAEPEdgeModule.java
packages/edge/android/src/main/java/com/adobe/marketing/mobile/reactnative/edge/RCTAEPEdgePackage.java

Edge - Reduce visibility for util classes

---

README.md

Merge staging -> consent branch and resolve conflicts

---

.github/workflows/npm-publish.yml

Fix an issue in release script. Here is the error information-> 
```
lerna notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. 
You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
```

Update release script to connect NPM register via https

---

apps/AEPSampleApp/android/app/src/main/java/com/aepsampleapp/MainApplication.java
apps/AEPSampleApp/android/build.gradle
apps/AEPSampleApp/extensions/EdgeIdentity.js
apps/AEPSampleApp/extensions/Identity.js
apps/AEPSampleApp/ios/Podfile.lock
packages/edge/android/src/main/java/com/adobe/marketing/mobile/reactnative/edge/RCTAEPEdgeArrayUtil.java
packages/edgeidentity/README.md
packages/edgeidentity/__tests__/AEPEdgeIdentityTests.ts
packages/edgeidentity/__tests__/AEPIdentityMapTests.ts
packages/edgeidentity/android/build.gradle
packages/edgeidentity/android/src/main/java/com/adobe/marketing/mobile/reactnative/edgeidentity/RCTAEPEdgeIdentityArrayUtil.java
packages/edgeidentity/android/src/main/java/com/adobe/marketing/mobile/reactnative/edgeidentity/RCTAEPEdgeIdentityDataBridge.java
packages/edgeidentity/android/src/main/java/com/adobe/marketing/mobile/reactnative/edgeidentity/RCTAEPEdgeIdentityMapUtil.java
packages/edgeidentity/android/src/main/java/com/adobe/marketing/mobile/reactnative/edgeidentity/RCTAEPEdgeIdentityModule.java
packages/edgeidentity/ios/src/RCTAEPEdgeIdentity.m
packages/edgeidentity/js/AEPIdentity.js
packages/edgeidentity/js/index.d.ts
packages/edgeidentity/js/models/AEPAuthenticatedState.js
packages/edgeidentity/js/models/AEPIdentityItem.js
packages/edgeidentity/js/models/AEPIdentityMap.js
tests/jest/setup.ts

Rebase with edgeidentity branch and resolved conflicts

---

apps/AEPSampleApp/android/app/src/main/java/com/aepsampleapp/MainApplication.java
apps/AEPSampleApp/android/build.gradle
apps/AEPSampleApp/extensions/EdgeIdentity.js
apps/AEPSampleApp/extensions/Identity.js
apps/AEPSampleApp/ios/Podfile.lock
packages/edge/android/src/main/java/com/adobe/marketing/mobile/reactnative/edge/RCTAEPEdgeArrayUtil.java
packages/edgeidentity/__tests__/AEPEdgeIdentityTests.ts
packages/edgeidentity/__tests__/AEPIdentityMapTests.ts
packages/edgeidentity/android/build.gradle
packages/edgeidentity/android/src/main/java/com/adobe/marketing/mobile/reactnative/edgeidentity/RCTAEPEdgeIdentityArrayUtil.java
packages/edgeidentity/android/src/main/java/com/adobe/marketing/mobile/reactnative/edgeidentity/RCTAEPEdgeIdentityDataBridge.java
packages/edgeidentity/android/src/main/java/com/adobe/marketing/mobile/reactnative/edgeidentity/RCTAEPEdgeIdentityMapUtil.java
packages/edgeidentity/android/src/main/java/com/adobe/marketing/mobile/reactnative/edgeidentity/RCTAEPEdgeIdentityModule.java
packages/edgeidentity/ios/src/RCTAEPEdgeIdentity.m
packages/edgeidentity/js/AEPIdentity.js
packages/edgeidentity/js/index.d.ts
packages/edgeidentity/js/models/AEPAuthenticatedState.js
packages/edgeidentity/js/models/AEPIdentityItem.js
packages/edgeidentity/js/models/AEPIdentityMap.js
tests/jest/setup.ts

Merging Android + JS code for Edge Identity, requires more iOS changes that will be added in a future PR.

Merge edgeidentity-apis -> edgeIdentity

---

apps/AEPSampleApp/App.js
apps/AEPSampleApp/extensions/ConsentView.js
packages/edgeconsent/RCTAEPEdgeConsent.podspec
packages/edgeconsent/README.md
packages/edgeconsent/__tests__/ConsentTests.ts
packages/edgeconsent/js/Consent.js
packages/edgeconsent/js/index.d.ts
packages/edgeconsent/js/index.js
packages/edgeconsent/package.json

Renaming from AEPConsent -> Consent

Consent - renaming public JS classes

---

packages/edgeidentity/README.md

Add more APIs
Include the link to gitbook EdgeIdentity FAQ 
Add info/link for when have core identity and EdgeIdentity in the same app.

Update Readme for EdgeIdentity

---

packages/edge/README.md

Update for a missing syntax section.

Readme Update

---

apps/AEPSampleApp/App.js
apps/AEPSampleApp/extensions/EdgeIdentityView.js
packages/edgeidentity/README.md
packages/edgeidentity/__tests__/IdentityMapTests.ts
packages/edgeidentity/__tests__/IdentityTests.ts
packages/edgeidentity/js/Identity.js
packages/edgeidentity/js/index.d.ts
packages/edgeidentity/js/index.js
packages/edgeidentity/js/models/AuthenticatedState.js
packages/edgeidentity/js/models/IdentityItem.js
packages/edgeidentity/js/models/IdentityMap.js

Renaming :
AEPIdentity -> Identity, 
AEPIdentityItem -> IdentityItem, 
AEPIdentityMap -> IdentityMap, 
AEPAuthenticatedState -> AuthenticatedState

Edge Identity - renaming public JS classes

---

apps/AEPSampleApp/ios/Podfile.lock
packages/edgeconsent/js/Consent.js

Consent - return promise fix 

---

packages/edgeidentity/__tests__/IdentityTests.ts
packages/edgeidentity/js/Identity.js
tests/jest/setup.ts

Convert native identity map  object to js identity map

Convert native identity map object to js identity map

---

packages/core/README.md
packages/core/__tests__/MobileCoreTests.ts
packages/core/js/MobileCore.js
packages/core/js/index.d.ts
tests/jest/setup.ts

Core - remove dispatchResponseEvent API

---

apps/AEPSampleApp/extensions/EdgeIdentityView.js
apps/AEPSampleApp/styles/styles.js
packages/edgeidentity/README.md

Remove Static from Readme

---

apps/AEPSampleApp/extensions/ConsentView.js
packages/edge/README.md
packages/edge/js/Edge.js
tests/jest/setup.ts

Add return promise custom type

Add return promise custom type

---

packages/edge/README.md
packages/edge/__tests__/EdgeTests.ts
packages/edge/js/Edge.js
packages/edge/js/index.d.ts
tests/jest/setup.ts

Fix return type for ts

---

packages/edgeidentity/__tests__/IdentityMapTests.ts
packages/edgeidentity/js/index.d.ts

Enum support for AuthenticatedState in ts.

Enum support for AuthenticatedState in ts

---

packages/edge/README.md
packages/edgeconsent/README.md
packages/edgeidentity/README.md

Update Readme with initializing information for  Edge extensions

Update Readme with initializing information for Edge extensions

---

packages/core/README.md
packages/userprofile/README.md

Update API reference for Core & Profile extensions

---

packages/userprofile/README.md

Quick fix for API heading style

---

packages/userprofile/android/src/main/java/com/adobe/marketing/mobile/reactnative/userprofile/RCTAEPUserProfileModule.java

[bug-fix] pass WritableMap to javascript code for profile's getter method

---

apps/AEPSampleApp/ios/Podfile.lock
apps/AEPSampleApp/package.json
packages/edge/package.json

Edge Beta.2 release

---

docs/migration.md
packages/core/README.md

Update API docs with typescript syntax (migration doc/ readme)

---

docs/migration.md
packages/core/README.md
packages/core/android/src/main/java/com/adobe/marketing/mobile/reactnative/RCTAEPIdentityModule.java

Update Identity Readme, migration doc
A Bug fix - On Android Null check for visitorId in getIdentifier. If it is null, set to empty array. This fixes a promise error when we call getIdentity without custom syncIdentifier.

Update Identity doc and fix

---

apps/AEPSampleApp/ios/Podfile.lock
apps/AEPSampleApp/package.json
packages/assurance/package.json
packages/core/package.json
packages/edge/package.json
packages/edgeconsent/package.json
packages/edgeidentity/package.json
packages/userprofile/package.json

1.0.0 release

---

.vscode/settings.json

remove extra file

---

apps/AEPSampleApp/ios/AEPSampleApp/AppDelegate.m
apps/AEPSampleApp/ios/Podfile.lock
apps/AEPSampleApp/package.json
package.json
yarn.lock

Update hoisting for Sample App

Update hoisting for Sample App

---

apps/AEPSampleApp/ios/AEPSampleApp/AppDelegate.m

Register missing extension in iOS sample app

Register missing extension in iOS sample app

---

apps/AEPSampleApp/android/app/src/main/java/com/aepsampleapp/MainApplication.java

Small fix to register Optimize in android sample app

Register optimize

---

apps/AEPSampleApp/ios/AEPSampleApp/AppDelegate.mm

Adds edge consent to ios sample app registration

fix: :bug: register edge consent on ios sample app

---

packages/optimize/README.md
packages/optimize/__tests__/OptimizeTests.ts
packages/optimize/__tests__/offer.json
packages/optimize/ts/models/Offer.ts

Allows meta information includes in platform response to be included in the offer class for end user.
Adds unit tests where appropriate

feat: includes meta information in offer

---

packages/optimize/__tests__/OptimizeTests.ts
packages/optimize/__tests__/offer.json
packages/optimize/android/src/main/java/com/adobe/marketing/mobile/reactnative/optimize/RCTAEPOptimizeUtil.java
packages/optimize/ios/src/RCTAEPOptimize.m
packages/optimize/ts/models/Offer.ts

Adds score field to offer class
Unit tests have been updated

feat: adds score to offer class, better type defs

---

.circleci/config.yml
packages/campaignclassic/android/src/main/java/com/adobe/marketing/mobile/reactnative/campaignclassic/RCTAEPCampaignClassicModule.java
packages/places/android/src/main/java/com/adobe/marketing/mobile/reactnative/places/RCTAEPPlacesDataBridge.java
packages/places/android/src/main/java/com/adobe/marketing/mobile/reactnative/places/RCTAEPPlacesModule.java
packages/target/android/src/main/java/com/adobe/marketing/mobile/reactnative/target/RCTAEPTargetDataBridge.java
packages/target/android/src/main/java/com/adobe/marketing/mobile/reactnative/target/RCTAEPTargetModule.java

https://github.com/adobe/aepsdk-react-native/issues/230
https://github.com/adobe/aepsdk-react-native/issues/228
https://github.com/adobe/aepsdk-react-native/issues/227

Fix Android 2.0 compilation errors in Target, Places and Campaign classic

---

packages/edgeconsent/README.md

Update consent readme doc for registration information

Update consent readme doc for registration information

---

packages/edgeconsent/README.md

consent -> staging

---

.circleci/config.yml
apps/AEPSampleApp/android/app/src/main/AndroidManifest.xml
apps/AEPSampleApp/extensions/EdgeView.tsx
apps/AEPSampleApp/ios/Podfile.lock
packages/edge/README.md
packages/edge/__tests__/EdgeTests.ts
packages/edge/android/src/main/java/com/adobe/marketing/mobile/reactnative/edge/RCTAEPEdgeModule.java
packages/edge/ios/src/RCTAEPEdge.m
packages/edge/ts/Edge.ts
packages/optimize/__tests__/OptimizeTests.ts
packages/target/__tests__/TargetTests.ts
tests/jest/setup.ts
yarn.lock

Add setLocationHint and getLocationHint to Edge Network extension (ts, Java and iOS)
Add unit tests
Update Sample App with location hint API
Update Sample App AndroidManifest file's deeplink format, so now it works for all Android API.
Update location hint API doc.

Add location hint APIs to Edge Network

---

packages/edgeconsent/README.md
packages/edgeidentity/README.md

Update EdgeIdentity readme registration info
Also update EdgeConsent format in the readme

Update EdgeIdentity readme registration info

---

packages/campaignclassic/android/src/main/java/com/adobe/marketing/mobile/reactnative/campaignclassic/RCTAEPCampaignClassicModule.java

update trackNotificationClickWithUserInfo to call CampaignClassic.trackNotificationClick

fix acc api call

---

README.md
apps/AEPSampleApp/ios/AEPSampleApp/AppDelegate.mm
docs/migration.md
packages/assurance/README.md
packages/campaignclassic/README.md
packages/messaging/README.md
packages/optimize/README.md
packages/places/README.md
packages/target/README.md

Update Migration doc

---

apps/AEPSampleApp/ios/AEPSampleApp/AppDelegate.mm

Register identity extension in sample app for iOS

Register identity extension in sample app

---

packages/edge/README.md
packages/edgebridge/README.md
packages/edgeconsent/README.md
packages/edgeidentity/README.md

minor formatting for the readme docs

minor formatting for the readme docs

---

.circleci/config.yml
README.md

- Updated the main Readme for the 5.0.0 release
- Disabled ios build step on CI to unblock the release workflow. An issue has been created for fixing it later. https://github.com/adobe/aepsdk-react-native/issues/272

Update Readme for the 5.0.0 release

---

.github/workflows/npm-publish.yml

[fix] use "yarn install" in the release action

---

packages/assurance/README.md

Fix assurance badge

---

docs/migration.md
packages/core/README.md
packages/core/package.json
packages/core/ts/MobileCore.ts

Add Edge Network and Edge Identity repo links in the Important block for track API.
User should be able to know the usage info of trackAPI -  using Edge Network and Edge Bridge. 
Edge Bridge readme explains detailed info about trackAPIs, so we put Edge Bridge link before Edge Network.
Also add a note in acptarget table the migration doc. Using Analytics for Target, the user should use Edge Network and Optimize.

Add Edge Network and Edge Bridge repo links in the Important block for track API

---

docs/migration.md

Update migration doc for Analytics workflow

Update migration doc for Analytics workflow

---

.github/workflows/npm-publish.yml

Upgrades node version in github action

fix: :arrow_up: upgrade node version in github action

---

.github/workflows/tag-beta.yml

Tag branch as beta appropriately

feat: :construction_worker: adds action to tag messaging

---

apps/AEPSampleApp/ios/Podfile.lock
packages/messaging/ios/src/RCTAEPMessagingDataBridge.swift
packages/messaging/src/index.ts
packages/messaging/src/models/MessagingPropositionItem.ts

Fixed cbe beta IOS not being able to build due to class changes

fix: :bug: fixes broken messaging build

---

.github/workflows/tag-beta.yml
apps/AEPSampleApp/ios/Podfile.lock
packages/messaging/ios/src/RCTAEPMessagingDataBridge.swift
packages/messaging/src/index.ts
packages/messaging/src/models/MessagingPropositionItem.ts

Merge down from main to staging

Merge down from main to staging

---

README.md

Add troubleshooting section in the readme for the known issues

Add troubleshooting section in the readme for the known issues

---

apps/AEPSampleApp/README.md

Updated troubleshooting guide for test app

---

apps/AEPSampleApp/extensions/EdgeView.tsx
apps/AEPSampleApp/ios/Podfile.lock
packages/edge/RCTAEPEdge.podspec
packages/edge/__tests__/EdgeTests.ts
packages/edge/android/build.gradle
packages/edge/android/src/main/java/com/adobe/marketing/mobile/reactnative/edge/RCTAEPEdgeDataBridge.java
packages/edge/ios/src/RCTAEPExperienceEventDataBridge.m
packages/edge/ts/Edge.ts
packages/edge/ts/models/ExperienceEvent.ts
packages/messaging/ios/src/RCTAEPMessagingDataBridge.swift
packages/messaging/src/index.ts
packages/messaging/src/models/MessagingPropositionItem.ts

Add datastreamIdOverride and datastreamConfOverride as the parameters for the ExperienceEvent.
It continue supports
Previous method: (May be we need to mark this soon be deprecated)
let experienceEvent = new ExperienceEvent(xdmData, data, datasetId);
New support methods:
// xdmData, data, dataIdentifier
let experienceEvent = new ExperienceEvent({
xdmData: xdmData,
data: data,
datasetIdentifier: datasetId,
});
//experienceEvent datastreamIdOverride support
let datastreamIdOverride = 'sampleDatastreamID';
let experienceEvent = new ExperienceEvent({
xdmData: xdmData,
data: data,
datastreamIdOverride: datastreamIdOverride,
});
//experienceEvent datastreamConfOverride support
let experienceEvent = new ExperienceEvent({
xdmData: xdmData,
data: data,
datastreamConfigOverride: configOverrides, …

Add datastreamIdOverride and datastreamConfOverride for ExperienceEvent

---

packages/edge/README.md
packages/edge/ts/models/ExperienceEvent.ts

Add id override feature into the Edge readme.

Add data stream override feature into the Edge readme

---

apps/AEPSampleApp/ios/Podfile.lock
apps/AEPSampleApp/package.json
packages/edge/package.json

Update Edge version to 5.1.0

---

apps/AEPSampleApp/extensions/EdgeView.tsx
packages/edge/README.md

update with review comments

---

README.md

Main -> Staging merge down

---

README.md
apps/AEPSampleApp/ios/AEPSampleApp/AppDelegate.mm
apps/AEPSampleApp/ios/Podfile.lock
packages/core/README.md
packages/core/ios/src/Core/RCTAEPCoreDataBridge.h
packages/edgebridge/README.md
packages/messaging/RCTAEPMessaging.podspec

Doc's update
podspec update
Update RCTAEPCoreDataBridge.h nullable info

Clean up update

---

README.md

Add Privacy manifest info to readme

Add Privacy manifest info to readme

---

README.md

Add a note for supported platforms in the Readme.

Add a note for supported platforms in the Readme

---

.npmignore
apps/AEPSampleApp/README.md

Fixes an issue if developer reload was initiated while `onPropositionUpdate` was listening, it would emit the event before the emitter was ready.

fix: 🐛 fixes issue with optimize event emitter

---

packages/messaging/android/src/main/java/com/adobe/marketing/mobile/reactnative/messaging/RCTAEPMessagingUtil.java
packages/messaging/package.json

Fixes an issue where new object properties in messaging proposition were throwing an error

fix: :bug: fixes conversion issue for messaging proposition on android

---

packages/campaignclassic/README.md

Corrected the import statement for the `CampaignClassic` extension in the README file.
The package name was incorrectly capitalized as `@adobe/react-native-AEPCampaignClassic`,
and it has now been fixed to `@adobe/react-native-aepcampaignclassic`.
No related open issue. This is a direct fix to the README to ensure developers use the correct import statement for the CampaignClassic extension.
This change was necessary because the incorrect capitalization in the import statement could confuse developers and lead to errors when integrating the CampaignClassic extension into their project.
This change corrects the documentation to ensure the proper import of the CampaignClassic extension. The fix has been verified by successfully invoking CampaignClassic APIs and confirming their output in …

Fix import statement in README for CampaignClassic extension

---

packages/optimize/README.md

Fix syntax in the Optimize.extensionVersion() code example, correcting the missing braces in the README.
No related open issue was found, as this is a direct fix for an error in the README code example.
This change was required to fix a syntax error in the code example, which could mislead developers or cause confusion. The correction ensures that the example works properly and follows best practices.
The corrected syntax has been verified locally by executing the Optimize.extensionVersion() API call and checking that the correct version is logged without syntax errors.

Fix missing parentheses in Optimize README code snippet

---

apps/AEPSampleApp/extensions/MessagingView.tsx
apps/AEPSampleApp/ios/Podfile.lock
packages/messaging/RCTAEPMessaging.podspec
packages/messaging/README.md
packages/messaging/ios/src/RCTAEPMessaging.swift
packages/messaging/ios/src/RCTAEPMessagingDataBridge.swift
packages/messaging/package.json
packages/messaging/src/Messaging.ts
packages/messaging/src/index.ts
packages/messaging/src/models/ContentCard.ts
packages/messaging/src/models/HTMLProposition.ts
packages/messaging/src/models/InAppMessage.ts
packages/messaging/src/models/JSONPropositionItem.ts
packages/messaging/src/models/Message.ts
packages/messaging/src/models/MessagingDelegate.ts
packages/messaging/src/models/MessagingEdgeEventType.ts
packages/messaging/src/models/PersonalizationSchema.ts
packages/messaging/src/models/ScopeDetails.ts

Adds support for content cards and other proposition types for react native

Messaging Content Card Support

---

apps/AEPSampleAppNewArchEnabled/app.json
apps/AEPSampleAppNewArchEnabled/app/AssuranceView.tsx
apps/AEPSampleAppNewArchEnabled/app/ConsentView.tsx
apps/AEPSampleAppNewArchEnabled/app/EdgeBridgeView.tsx
apps/AEPSampleAppNewArchEnabled/app/EdgeView.tsx
apps/AEPSampleAppNewArchEnabled/app/_layout.tsx
apps/AEPSampleAppNewArchEnabled/app/index.tsx

navigation structure fixes

---

apps/AEPSampleAppNewArchEnabled/app/OptimizeView.tsx
apps/AEPSampleAppNewArchEnabled/ios/Podfile.lock
apps/AEPSampleAppNewArchEnabled/package.json
apps/AEPSampleAppNewArchEnabled/yarn.lock
yarn.lock

https://jira.corp.adobe.com/browse/MOB-22144

optimize integration

---

apps/AEPSampleAppNewArchEnabled/android/app/src/main/java/com/AEPSampleAppNewArchEnabled/MainActivity.kt
apps/AEPSampleAppNewArchEnabled/android/app/src/main/java/com/AEPSampleAppNewArchEnabled/MainApplication.kt
apps/AEPSampleAppNewArchEnabled/ios/AEPSampleAppNewArchEnabled/AdobeBridge.h
apps/AEPSampleAppNewArchEnabled/ios/AEPSampleAppNewArchEnabled/AdobeBridge.m
apps/AEPSampleAppNewArchEnabled/ios/AEPSampleAppNewArchEnabled/AppDelegate.mm

https://jira.corp.adobe.com/browse/MOB-22349

Lifecycle implementation

---

apps/AEPSampleAppNewArchEnabled/app/IdentityView.tsx
package.json
yarn.lock

https://jira.corp.adobe.com/browse/MOB-22365

identity integration with fixes

---

packages/messaging/android/src/main/java/com/adobe/marketing/mobile/reactnative/messaging/RCTAEPMessagingModule.java
packages/messaging/android/src/main/java/com/adobe/marketing/mobile/reactnative/messaging/RCTAEPMessagingUtil.java

https://jira.corp.adobe.com/browse/PLATIR-46274

fix RCTAEPMessagingModule getLatestMessage and getCachedMessages

---

packages/messaging/package.json

Update Messaging Version to 6.0.5 for the release

Messaging Version to 6.0.5

---

packages/places/android/src/main/java/com/adobe/marketing/mobile/reactnative/places/RCTAEPPlacesModule.java

https://jira.corp.adobe.com/browse/MOB-22553
This fix is necessary to make. it compatible with new architecture of react native

places native module name fixes in android

---

packages/places/android/src/main/java/com/adobe/marketing/mobile/reactnative/places/RCTAEPPlacesModule.java

This reverts commit a4663f0de62fa487127557c92fdb6f8f916784ab.

Revert "places native module name fixes in android (#412)"

---

packages/places/android/src/main/java/com/adobe/marketing/mobile/reactnative/places/RCTAEPPlacesModule.java

places native module name fixes in android (#412)

---

packages/places/android/src/main/java/com/adobe/marketing/mobile/reactnative/places/RCTAEPPlacesModule.java

native places module fixes

---

apps/AEPSampleAppNewArchEnabled/app/index.tsx

Added places target navigation on main home page

---

packages/places/package.json

bump version from 6.0.2 to 6.0.3

---

README.md

Update repo read me for new arch

added new arch read me

---

apps/AEPSampleAppNewArchEnabled/app/_layout.tsx
apps/AEPSampleAppNewArchEnabled/app/index.tsx

Align extension view names with older arc sample app for consistency

---

README.md

Update Readme doc

---

packages/messaging/README.md

https://jira.corp.adobe.com/browse/MOB-22883
Screenshot for QA

removed unsupported api

---

packages/optimize/android/build.gradle
packages/optimize/android/src/main/java/com/adobe/marketing/mobile/reactnative/optimize/RCTAEPOptimizeUtil.java

https://jira.corp.adobe.com/browse/MOB-22881

optimize int to double conversion

---

apps/AEPSampleAppNewArchEnabled/ios/Podfile.lock
packages/optimize/package.json
yarn.lock

version bump 6.0.3 -> 6.1.0

---

apps/AEPSampleAppNewArchEnabled/package.json
yarn.lock

sample apps yarn lock fixes

---

apps/AEPSampleAppNewArchEnabled/ios/Podfile.lock
packages/assurance/android/build.gradle
packages/campaignclassic/android/build.gradle
packages/core/RCTAEPCore.podspec
packages/core/android/build.gradle
packages/edge/android/build.gradle
packages/edgebridge/android/build.gradle
packages/edgeconsent/android/build.gradle
packages/edgeidentity/android/build.gradle
packages/messaging/android/build.gradle
packages/optimize/android/build.gradle
packages/places/android/build.gradle
packages/target/android/build.gradle
packages/userprofile/android/build.gradle

bom integration and ios core dependency update

---

apps/AEPSampleApp/App.tsx
apps/AEPSampleApp/README.md
apps/AEPSampleAppNewArchEnabled/README.md
apps/AEPSampleAppNewArchEnabled/app/_layout.tsx
packages/core/README.md

initialize api example usage updated along with usage guidelines for both sample apps

Simplification api call docs

---

README.md
apps/AEPSampleApp/App.tsx
apps/AEPSampleAppNewArchEnabled/app/_layout.tsx
packages/assurance/README.md
packages/core/README.md
packages/core/src/models/InitOptions.ts

Assurance read me updates along with other  docs related fixes

docs fixes

---

apps/AEPSampleAppNewArchEnabled/ios/Podfile.lock
packages/edgebridge/RCTAEPEdgeBridge.podspec
packages/edgebridge/package.json

Add Edge Bridge TVOS support 

---

apps/AEPSampleAppNewArchEnabled/ios/Podfile.lock
packages/edgebridge/RCTAEPEdgeBridge.podspec
packages/edgebridge/package.json

DOWN MERGE

---

packages/places/android/build.gradle
packages/places/package.json

location services updates

---

packages/messaging/package.json

update messaging SDK version

---

packages/messaging/tutorials/ContentCards.md

Updates tracking methods inside CC tutorial with new api by @ishita-gambhir-adobe

docs: update ContentCards tutorial to use new trackContentCardInteraction methods from PR #477

---

packages/messaging/README.md
packages/messaging/tutorials/ContentCards.md

Merge main to staging and resolve conflicts

---

packages/messaging/package.json

messaging version bump for 7.2.0 release
