apps/AEPSampleApp/extensions/Assurance.js
packages/edge/package.json

Update edge package.json with edgeidentity as dependency
Add copyright info to Assurance.js

Update edge package.json and add copyright info

---

packages/edge/README.md

Update Edge Wrapper Readme

---

apps/AEPSampleApp/extensions/Core.js
apps/AEPSampleApp/ios/Podfile.lock
apps/AEPSampleApp/package.json
packages/core/__tests__/AEPCoreTests.ts
packages/core/android/src/main/java/com/adobe/marketing/mobile/reactnative/RCTAEPCoreModule.java
packages/core/ios/src/Core/RCTAEPCore.m
packages/core/js/AEPCore.js
packages/core/js/index.d.ts
packages/core/package.json
tests/jest/setup.ts
yarn.lock

add a new API in Core - resetIdentities

---

packages/edgeidentity/README.md
packages/edgeidentity/android/src/main/java/com/adobe/marketing/mobile/reactnative/edgeidentity/RCTAEPEdgeIdentityModule.java
packages/edgeidentity/ios/src/RCTAEPEdgeIdentity.m
packages/edgeidentity/js/AEPIdentity.js

Add promise checking for error case

Add promise checking for error case

---

packages/edgeidentity/android/src/main/java/com/adobe/marketing/mobile/reactnative/edgeidentity/RCTAEPEdgeIdentityDataBridge.java
packages/edgeidentity/ios/src/RCTAEPEdgeIdentity.m
packages/edgeidentity/ios/src/RCTAEPEdgeIdentityDataBridge.h
packages/edgeidentity/ios/src/RCTAEPEdgeIdentityDataBridge.m

Edge Identity iOS implementation

Edge Identity iOS implementation

---

packages/core/__tests__/IdentityTests.ts
packages/core/__tests__/MobileCoreTests.ts
packages/core/js/index.d.ts
tests/jest/setup.ts

Core  - add enum support in d.ts file

---

packages/userprofile/README.md

Add registering extensions example in UserProfile README

---

packages/edge/android/src/main/java/com/adobe/marketing/mobile/reactnative/edge/RCTAEPEdgeArrayUtil.java
packages/edge/android/src/main/java/com/adobe/marketing/mobile/reactnative/edge/RCTAEPEdgeMapUtil.java

Add Arraylist support in WriteableArray for Android.
If response payload has arraylist in it, it can be extracted now.

Add Arraylist support in WriteableArray

---

apps/AEPSampleApp/android/app/src/debug/AndroidManifest.xml

Add android manifest to sample app debug folder, it was broken launching with metro on Android platform.

add android manifest back to Sample App debug folder

---

.circleci/config.yml
apps/AEPSampleApp/android/app/src/main/AndroidManifest.xml
apps/AEPSampleApp/android/app/src/main/java/com/aepsampleapp/MainApplication.java
apps/AEPSampleApp/babel.config.js
apps/AEPSampleApp/extensions/EdgeIdentityView.tsx
apps/AEPSampleApp/ios/AEPSampleApp/AppDelegate.m
apps/AEPSampleApp/ios/Podfile.lock
apps/AEPSampleApp/package-lock.json
apps/AEPSampleApp/package.json
packages/edgeidentity/README.md
packages/edgeidentity/__tests__/IdentityTests.ts
packages/edgeidentity/android/src/main/java/com/adobe/marketing/mobile/reactnative/edgeidentity/RCTAEPEdgeIdentityModule.java
packages/edgeidentity/ios/src/RCTAEPEdgeIdentity.m
packages/edgeidentity/package.json
packages/edgeidentity/ts/Identity.ts
tests/jest/setup.ts
yarn.lock

Add getUrlVariables API
Add getUrlVariables API,  update sample app, update doc.

Add getUrlVariables API to EdgeIdentity package

---

.circleci/config.yml
packages/optimize/README.md
packages/optimize/android/src/main/java/com/adobe/marketing/mobile/reactnative/optimize/RCTAEPOptimizeModule.java

This is a small fix that removes a console warning on android apps due to the package not having add and remove listener functions react native looks for in android. Functionality is not affected.
Previous warning:

fix: removes android warning using event emitter

---

.circleci/config.yml

Updates circleci xcode build version to 13, adds workaround to deal with circleci xcode naming. See linked issue for details.
https://github.com/adobe/aepsdk-react-native/issues/196
The current xcode version in the build will be deprecated on Aug 2, and all ios builds will fail afterwards.
Ran successfully in CircleCI!

Circleci update xcode

---

packages/assurance/README.md
packages/assurance/package.json
packages/campaignclassic/README.md
packages/campaignclassic/package.json
packages/core/README.md
packages/core/package.json
packages/edge/README.md
packages/edge/package.json
packages/edgeconsent/README.md
packages/edgeconsent/package.json
packages/edgeidentity/README.md
packages/edgeidentity/package.json
packages/messaging/README.md
packages/messaging/package.json
packages/optimize/README.md
packages/optimize/package.json
packages/places/README.md
packages/places/package.json
packages/target/README.md
packages/target/package.json
packages/userprofile/README.md
packages/userprofile/package.json

Update Readme for Edge and Edge Identity APIs.
Replace all https://aep-sdks.gitbook.io/docs/ to adobe.io docs for all extensions in Readme and Package.json.

Update doc links

---

packages/assurance/android/build.gradle
packages/campaignclassic/android/build.gradle
packages/core/android/build.gradle
packages/edge/android/build.gradle
packages/edgeconsent/android/build.gradle
packages/edgeidentity/android/build.gradle
packages/messaging/android/build.gradle
packages/optimize/android/build.gradle
packages/places/android/build.gradle
packages/target/android/build.gradle
packages/userprofile/android/build.gradle

The Android `build.gradle` files for each package here have hard-coded values for the `compileSdkVersion`, `minSdkVersion`, and `targetSdkVersion`.  This causes build errors with React Native 0.70.6:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':adobe_react-native-aepuserprofile:processDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.facebook.react:react-native:0.70.6] /Users/kdice/.gradle/caches/transforms-3/4b3c55c96a7b7307f23241c80fa0f0d7/transformed/jetified-react-native-0.70.6-debug/AndroidManifest.xml as the library might be using APIs not available in 16
Suggestion: use a compatible library with a minSdk of at most 16,
or increase this project's …
```

fix: defer to root project's Android sdk version gradle params

---

packages/edge/README.md
packages/edgeidentity/README.md

Remove semi-colon in doc Syntax for the consistency with other extensions.

Remove semi-colon for Syntax in the doc

---

apps/AEPSampleApp/extensions/OptimizeView.tsx
packages/places/android/src/main/java/com/adobe/marketing/mobile/reactnative/places/RCTAEPPlacesDataBridge.java
packages/places/ios/src/RCTAEPPlacesDataBridge.m

Review updates

---

.circleci/config.yml
apps/AEPSampleApp/ios/AEPSampleApp.xcodeproj/project.pbxproj
apps/AEPSampleApp/ios/Podfile

bring ios sample app back to ci
- unchecked "Based on dependency analysis" in the Xcode build phrase to dismiss the build error.
- Calling react-native run-ios command directly instead of from yarn script

bring ios sample app back to ci

---

packages/core/__tests__/MobileCoreTests.ts

remove deprecated API in the unit test

remove deprecated API in the unit test

---

.github/ISSUE_TEMPLATE/bug_report.yml
apps/AEPSampleApp/android/build.gradle
apps/AEPSampleApp/extensions/CoreView.tsx
apps/AEPSampleApp/extensions/EdgeView.tsx
packages/core/__tests__/MobileCoreTests.ts
packages/core/android/src/main/java/com/adobe/marketing/mobile/reactnative/RCTAEPCoreModule.java
packages/core/ios/src/Core/RCTAEPCore.m
packages/core/ts/MobileCore.ts
packages/messaging/RCTAEPMessaging.podspec

Add dispatchEventWithResponseCallback(event: Event, timeoutMS: Number): Promise<Event> ()
Remove dispatchEventWithResponseCallback(event: Event): Promise<Event> ()
Including few changes from the earlier PR review.
Add dispatchEvent API back

Update dispatchEventWithResponseCallback API with timeout param

---

apps/AEPSampleApp/extensions/OptimizeView.tsx
apps/AEPSampleApp/extensions/TargetView.tsx
apps/AEPSampleApp/types/props.ts
packages/assurance/package.json
packages/campaignclassic/package.json
packages/core/package.json
packages/edge/package.json
packages/edgebridge/package.json
packages/edgeconsent/package.json
packages/edgeidentity/package.json
packages/messaging/package.json
packages/optimize/package.json
packages/places/package.json
packages/target/package.json
packages/userprofile/package.json

Fix typescript declaration files on packages
Fix typescript issues of sample app `AEPSampeApp`
Fixed fields `main` and add `types` fields to `package.json` files of `packages/*`, example:
file: packages/campaignclassic/package.json
**current**
```
{
"name": "@adobe/react-native-aepcampaignclassic",
"version": "6.0.1",
"description": "Experience Platform Campaign Classic extension for Adobe Experience Platform Mobile SDK. Written and Supported by Adobe.",
"homepage": "https://developer.adobe.com/client-sdks/documentation/",
"license": "Apache-2.0",
"main": "./ts/index.ts",
"scripts": {
"cleanup": "rm -rf node_modules",
"tsc": "tsc"
},
```
**fixed**
```
{
"name": "@adobe/react-native-aepcampaignclassic",
"version": "6.0.1",
"description": "Experience Platform Campaign Classic extension for …
```

Fix typescript types

---

README.md
packages/optimize/README.md

build error optimize read me updated

---

README.md
packages/optimize/README.md
packages/places/android/build.gradle
packages/places/package.json

* build error optimize read me updated
* optimize note added
* enable TVOS platform for Edge Bridge
enable TVOS platform for Edge Bridge
* update app podfile to the latest versions
update app podfile to the latest versions
* updated optimize read me for build errors
* location services updates (#475)
* location services updates
* places version bump
---------

Merge Main to Staging (Places sdk release) (#476)

---

packages/messaging/README.md
packages/messaging/tutorials/ContentCards.md

Adds a tutorial doc for fetching and rendering content cards

Content cards tutorial

---

.gitignore
apps/AEPSampleAppNewArchEnabled/app/MessagingView.tsx
packages/messaging/README.md
packages/messaging/__tests__/MessagingTests.ts
packages/messaging/android/src/main/java/com/adobe/marketing/mobile/reactnative/messaging/RCTAEPMessagingModule.java
packages/messaging/android/src/main/java/com/adobe/marketing/mobile/reactnative/messaging/RCTAEPMessagingUtil.java
packages/messaging/ios/src/RCTAEPMessaging.mm
packages/messaging/ios/src/RCTAEPMessaging.swift
packages/messaging/src/Messaging.ts
tests/jest/setup.ts

add support for content card tracking

---

apps/AEPSampleAppNewArchEnabled/app/MessagingView.tsx
packages/messaging/README.md
packages/messaging/__tests__/MessagingTests.ts
packages/messaging/android/src/main/java/com/adobe/marketing/mobile/reactnative/messaging/RCTAEPMessagingConstants.java
packages/messaging/android/src/main/java/com/adobe/marketing/mobile/reactnative/messaging/RCTAEPMessagingModule.java
packages/messaging/ios/src/RCTAEPMessaging.mm
packages/messaging/ios/src/RCTAEPMessaging.swift
packages/messaging/ios/src/RCTAEPMessagingConstants.swift
packages/messaging/src/Messaging.ts
packages/messaging/tutorials/In-App Messaging.md
tests/jest/setup.ts

add handleJavascriptMessage in AEPMessaging

add handleJavascriptMessage in AEPMessaging

---

packages/authoring-ui/__tests__/convertImageOnlyContent.test.ts

Update image only test

---

apps/AEPSampleAppNewArchEnabled/app/OptimizeView.tsx
apps/AEPSampleAppNewArchEnabled/app/_layout.tsx
packages/optimize/README.md
packages/optimize/__tests__/OptimizeTests.ts
packages/optimize/android/src/main/java/com/adobe/marketing/mobile/reactnative/optimize/RCTAEPOptimizeConstants.java
packages/optimize/android/src/main/java/com/adobe/marketing/mobile/reactnative/optimize/RCTAEPOptimizeModule.java
packages/optimize/android/src/main/java/com/adobe/marketing/mobile/reactnative/optimize/RCTAEPOptimizeUtil.java
packages/optimize/ios/src/RCTAEPOptimize.m
packages/optimize/src/Optimize.ts
packages/optimize/src/models/Offer.ts
packages/optimize/src/models/Proposition.ts
tests/jest/setup.ts

Add APIs for batch displayed and generateDisplayInteractionXDM for multiple offers.

add displayed and generateDisplayInteractionXDM APIs for multiple offers

---

packages/messaging/README.md
packages/messaging/src/Messaging.ts

read me updates regarding deprecated apis

---

apps/AEPSampleAppNewArchEnabled/app/MessagingView.tsx
packages/messaging/README.md
packages/messaging/src/Messaging.ts

[Messaging] typecast Messaging Proposition for getPropositionsForSurface API
